# Estadística descriptiva

## Ejercicio 1

><span style="color:red; font-size: 20px;">**EJEMPLO**</span>

### Análisis variables cualitativas

```{r}
# Muestra
grades <- c("A", "B", "A", "C", "B", "A", "A", "C", "B", "A", "A", "A", "B", "C")

# Crear una tabla de frecuencias utilizando la función table()
freq_table <- table(grades)
freq_table
```

```{r}
# Creat gráfico de barras utilizando barplot()
barplot(freq_table, main = "Grade Distribution", xlab = "Grades", ylab = "Frequency", col = "skyblue")
```

```{r}
# Muestra datos
fruits <- c("Apples", "Bananas", "Oranges", "Grapes", "Mangoes")
percentages <- c(30, 25, 20, 15, 10)

# Crear un gráfico circular utilizando pie()
pie(percentages, labels = fruits, main = "Fruit Distribution")
```

### Análisis variable cuantitativas

```{r}
# Datos de muestra (puntuaciones de exámenes)
scores <- c(85, 92, 88, 78, 95, 89, 84, 90, 86, 93)

# Calcula la puntuación media (promedio)
mean_score <- mean(scores)
mean_score

# Calcula la puntuación mediana
median_score <- median(scores)
median_score 

# Calcula las puntuaciones mínimas y máximas
min_score <- min(scores)
min_score
max_score <- max(scores)
max_score

# Calcula el rango de puntuaciones
score_range <- max_score - min_score
score_range

# Calcula la desviación estándar de las puntuaciones
score_sd <- sd(scores)
score_sd

# Calcula el primer cuartil (Q1)
q1 <- quantile(scores, 0.25)
q1

# Calcula el tercer cuartil (Q3)
q3 <- quantile(scores, 0.75)
q3

# Calcula el rango intercuartil (IQR)
iqr <- q3 - q1
iqr

# Calcula la varianza
var(scores)

# calcula el coeficiente de variación

sd_cal <- sd(scores)
media_cal <- mean(scores)
CV <- sd_cal/media_cal*100
CV
```

```{r, include=FALSE}
# Generar una función, pues R no tiene una función propia para calcular la moda. 
getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}

a <- c(45, 35, 32, 78, 79, 67, 32)
getmode(a)
```

```{r}
# Datos de muestra (puntuaciones de pruebas)
scores <- c(85, 92, 88, 78, 95, 89, 84, 90, 86, 93)

# Calcular la media de la muestra
sample_mean <- mean(scores)

# Calcular el tamaño de la muestra
sample_size <- length(scores)

# Calcular la desviación estándar de la muestra
sample_sd <- sd(scores)

# Calcular el erro estándar de la muestra (SEM)
SEM <- sample_sd / sqrt(sample_size)

cat("Media de la muestra:", sample_mean, "\n")
cat("Error estandard de la media (SEM):", SEM)
```

[@Gonzalez2020; @Kabacoff2015]

## References

<div id="refs"></div>


