# Estadistica descriptiva

## Ejercicio 1

><span style="color:red; font-size: 20px;">**EJEMPLO**</span>

Determinar la tabla de frecuencias y varios tipos de gráficos.

```{r}
# Muestra
grades <- c("A", "B", "A", "C", "B", "A", "A", "C", "B", "A", "A", "A", "B", "C")

# Crear una tabla de frecuencias utilizando la función table()
freq_table <- table(grades)

# Mostrar la table de frecuencia
print(freq_table)
```

```{r}
# Creat gráfico de barras utilizando barplot()
barplot(freq_table, main = "Grade Distribution", xlab = "Grades", ylab = "Frequency", col = "skyblue")
```

```{r}
# Muestra datos
fruits <- c("Apples", "Bananas", "Oranges", "Grapes", "Mangoes")
percentages <- c(30, 25, 20, 15, 10)

# Crear un gráfico circular utilizando pie()
pie(percentages, labels = fruits, main = "Fruit Distribution")
```

## Ejercicio 2

><span style="color:red; font-size: 20px;">**EJEMPLO**</span>

Cálculo de medidas de tendencia central: media, mediana y moda. 

```{r }
a <- c(2.3, 2.15, 3.50, 2.60, 2.75, 2.82, 4.05, 2.25, 2.68, 3.00, 4.2, 2.85)
mean(a)

b <- c(2.3, 2.15, 3.50, 2.60, 2.75, 2.82, 4.05, 2.25, 2.68, 3.00, 40.2, 2.85)
mean(b)
```

```{r, size = "tiny"}
a <-  c(45, 35, 32, 79, 67)
median(a)

b <- c(45, 35, 32, 79, 79)
median(b)

c <- c(45, 35, 32, 7900, 67)
median(c)

d <- c(32, 35, 45, 59, 67, 79)
median(d)
```

```{r, include=FALSE}
# Generar una función, pues R no tiene una función propia para calcular la moda. 
getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}

a <- c(45, 35, 32, 78, 79, 67, 32)
getmode(a)
```



